### ISSUE TITLE
Boundary condition format upd, spelling mistakes, growth-type=2, log and other

### ISSUE THREAD

**Issue by okmechak** [okmechak/RiverSim#30]
+ [x] help: biffurcation -> bifuration, funciton -> function
- [x] default fieldValue=0
- [ ] mierzenie czasu
- [ ] !!! boundary condition - niepotrzebna opcja, zamiast tego na stałe, np. 0 - zerowa wartość pola, 1 - niezerowa wartość pola, 2 - zerowy strumień, 3 - niezerowy strumień (dodatkowa opcja boundaryFluxValue/boundaryFieldValue do ustawienia wartości strumienia pola / pola na górze, default 1/50) !!!
- [x] growth-type -> {dx,dy} nie działa, po kilku krokach zawraca drzewo i zaczyna rosnąć w kierunku ujemnym...?
- [ ] jak dokładnie działa algorytm (znajdowanie prędkości średniej w kolejnych iteracjach?)
- [x] verbose: --------#1------------w przypadku growth, tak jak w backward analyse;  i aktualna wysokość 
- [x] maximalHeight i numberOfSteps w sekcji Model w json
- [x] co robi suppress?
- [x] verbose: itteration

**Comment by okmechak** [comment]
"funciton -> function" nie znalazlem tego

**Comment by okmechak** [comment]
>boundary condition - niepotrzebna opcja, zamiast tego na stałe, np. 0 - zerowa wartość pola, 1 - niezerowa wartość pola, 2 - zerowy strumień, 3 - niezerowy strumień (dodatkowa opcja boundaryFluxValue/boundaryFieldValue do ustawienia wartości strumienia pola / pola na górze, default 1/50)

te zadanie troche rozrosnie sie.. 

jezeli teraz, mamy taka strukture:
```
"lines": [
            [
                0,
                1,
                1
            ],
```
zmrobie cos takiego
```
"lines": [
            [
                0,
                1,
                0, # <- zero oznacza dirichlet
                0.1 # <- a to jego znaczenie
            ],
            [
                1,
                2,
                1, #<-oznacza Neumana
                2.3 # <- i tez jego znaczenie
            ],
```

upd: i bede kontynuowac go tu: #10

**Comment by okmechak** [comment]
>maximalHeight i numberOfSteps w sekcji Model w json

Patrz w JSONie:
Model->ProgramOptions

**Comment by okmechak** [comment]
mierzenie czasu daley bedzie tutaj -> #16

**Comment by stzukowski** [comment]
> "funciton -> function" nie znalazlem tego

przedostatnia sekcja helpa (poprawki pogrubione) ->  "Mesh refinment parameters. Funciton of area constaint and its parameters: min_area - (max_area - min_area)*(1 - exp( - 1/(2*{mesh-sigma}^2)*(r/ro)^{mesh-exp})/(1 + exp( -1/(2*{mesh-sigma}^2)*(r/ro)^{mesh-exp}). options:" ->  "Mesh refinment parameters. **Function** of area **constraint** and its parameters: min_area - (max_area - min_area)*(1 - exp( - 1/(2*{mesh-sigma}^2)*(r/ro)^{mesh-exp})/(1 + exp( -1/(2*{mesh-sigma}^2)*(r/ro)^{mesh-exp}). _**Options**_:"

**Comment by okmechak** [comment]
Ok, drobniejsze zrobilem, czas i brzegi, bede na dniach kontynuowac
